{{- if and (not (index .Values "casepack-api" "secrets" "existingSecret")) (index .Values "casepack-api" "secrets" "activationBundle") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casepack.fullname" . }}-activation
  labels:
    {{- include "casepack.labels" . | nindent 4 }}
type: Opaque
data:
  activation.json: {{ index .Values "casepack-api" "secrets" "activationBundle" | b64enc | quote }}
{{- end }}
