{{- if and .Values.keycloak.enabled (not .Values.keycloak.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casepack.keycloakSmtpSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "casepack.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_SMTP_HOST: {{ .Values.keycloak.smtp.host | quote }}
  KC_SMTP_PORT: {{ .Values.keycloak.smtp.port | quote }}
  KC_SMTP_FROM: {{ .Values.keycloak.smtp.from | quote }}
  KC_SMTP_FROM_DISPLAY_NAME: {{ .Values.keycloak.smtp.fromDisplayName | quote }}
  KC_SMTP_AUTH: {{ .Values.keycloak.smtp.auth | quote }}
  KC_SMTP_USER: {{ .Values.keycloak.smtp.user | quote }}
  KC_SMTP_PASSWORD: {{ .Values.keycloak.smtp.password | quote }}
  KC_SMTP_STARTTLS: {{ .Values.keycloak.smtp.starttls | quote }}
  KC_SMTP_SSL: {{ .Values.keycloak.smtp.ssl | quote }}
{{- end }}
