{{- if and (not (index .Values "casepack-api" "secrets" "existingSecret")) (index .Values "casepack-api" "secrets" "licenseTokenFile") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casepack.fullname" . }}-license
  labels:
    {{- include "casepack.labels" . | nindent 4 }}
type: Opaque
data:
  license.jwt: {{ index .Values "casepack-api" "secrets" "licenseTokenFile" | b64enc | quote }}
{{- end }}
