apiVersion: v2
name: casepack-docs
description: CasePack Docs — Documentation for CasePack - Incident reporting, evidence management for MSPs.
type: application
version: 0.3.0
appVersion: "0.3.0"
home: https://docs.casepack.app
icon: https://casepack.app/apple-touch-icon.png
keywords:
  - casepack
  - documentation
sources:
  - https://github.com/bysamio/casepack-docs
maintainers:
  - name: bysamio
    email: admin@bysam.io
annotations:
  artifacthub.io/license: Proprietary
  artifacthub.io/category: security
