{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casepack-api.fullname" . }}
  labels:
    {{- include "casepack-api.labels" . | nindent 4 }}
type: Opaque
data:
  DB_URL: {{ .Values.secrets.dbUrl | b64enc | quote }}
  DB_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
  DB_PASS: {{ .Values.secrets.dbPass | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
  {{- if .Values.secrets.licenseToken }}
  CASEPACK_LICENSE_TOKEN: {{ .Values.secrets.licenseToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.licensePublicKey }}
  CASEPACK_LICENSE_PUBLIC_KEY: {{ .Values.secrets.licensePublicKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.provisioningSecret }}
  CASEPACK_PROVISIONING_SECRET: {{ .Values.secrets.provisioningSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.testDataResetHmacSecret }}
  CASEPACK_TEST_DATA_RESET_HMAC_SECRET: {{ .Values.secrets.testDataResetHmacSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.keycloakSaClientId }}
  CASEPACK_KEYCLOAK_SA_CLIENT_ID: {{ .Values.secrets.keycloakSaClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.keycloakSaClientSecret }}
  CASEPACK_KEYCLOAK_SA_CLIENT_SECRET: {{ .Values.secrets.keycloakSaClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
