apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.wordpressPassword }}
  wordpress-password: {{ .Values.wordpressPassword | b64enc | quote }}
  {{- else }}
  wordpress-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
  mariadb-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.smtpPassword (not .Values.smtpExistingSecret) }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{- end }}