apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primary.fullname" . }}-headless
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with .Values.primary.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: {{ .Values.primary.service.ports.postgresql }}
      targetPort: tcp-postgresql
      protocol: TCP
  selector:
    {{- include "postgresql.primary.selectorLabels" . | nindent 4 }}
