{{- $primaryHeadlessEnabled := eq (include "mariadb.primary.headlessEnabled" .) "true" -}}
{{- if $primaryHeadlessEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "mariadb.primary.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.primary.service.headless.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.primary.service.headless.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.primary.service.headless.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: {{ .Values.primary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
  selector:
    {{- include "mariadb.primary.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if eq .Values.architecture "replication" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "mariadb.secondary.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.kubernetes.io/component: secondary
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.secondary.service.headless.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secondary.service.headless.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secondary.service.headless.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: {{ .Values.secondary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
  selector:
    {{- include "mariadb.secondary.selectorLabels" . | nindent 4 }}
{{- end }}