{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "keycloak.fullname" . }}
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetCPU }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetMemory }}
    {{- end }}
  {{- if or .Values.autoscaling.hpa.behavior.scaleUp.policies .Values.autoscaling.hpa.behavior.scaleDown.policies }}
  behavior:
    {{- if .Values.autoscaling.hpa.behavior.scaleUp.policies }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.hpa.behavior.scaleUp.selectPolicy }}
      policies:
        {{- toYaml .Values.autoscaling.hpa.behavior.scaleUp.policies | nindent 8 }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.behavior.scaleDown.policies }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.hpa.behavior.scaleDown.selectPolicy }}
      policies:
        {{- toYaml .Values.autoscaling.hpa.behavior.scaleDown.policies | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
