{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ .Values.auth.adminPassword | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "keycloak.fullname" .) }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.externalDatabase.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.externalDatabase.password }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.tls.enabled (or .Values.tls.keystorePassword .Values.tls.truststorePassword) (not .Values.tls.passwordsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls-passwords" (include "keycloak.fullname" .) }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.tls.keystorePassword }}
  tls-keystore-password: {{ .Values.tls.keystorePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.truststorePassword }}
  tls-truststore-password: {{ .Values.tls.truststorePassword | b64enc | quote }}
  {{- end }}
{{- end }}
